-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.assets DROP CONSTRAINT IF EXISTS "fk_holder_Iid";



DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    username character varying(255)[] NOT NULL,
    email character varying(255)[] NOT NULL,
    password character varying(255)[] NOT NULL,
    balance numeric(10, 2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_username UNIQUE (username),
    CONSTRAINT unique_email UNIQUE (email)
);

DROP TABLE IF EXISTS public.assets;

CREATE TABLE IF NOT EXISTS public.assets
(
    id serial NOT NULL,
    date timestamp with time zone NOT NULL,
    name character varying(255)[] NOT NULL,
    description character varying(255),
    price numeric(10, 2) NOT NULL,
    holder_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.assets
    ADD CONSTRAINT "fk_holder_Iid" FOREIGN KEY (holder_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;